import { v4 as uuid } from "uuid";
import { chair, lamp, shelf, coffeeTable } from "../../assets/index";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "item 1",
    subtitle: "subtitle",
    price: "1100",
    categoryName: "category1",
    rating: 1.5,
    discount: 55,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 2",
    subtitle: "subtitle",
    price: "4100",
    categoryName: "category2",
    rating: 2.5,
    discount: 15,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 3",
    subtitle: "subtitle",
    price: "6400",
    categoryName: "category3",
    rating: 3.5,
    discount: 23,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 4",
    subtitle: "subtitle",
    price: "7700",
    categoryName: "category4",
    rating: 4.5,
    discount: 40,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 5",
    subtitle: "subtitle",
    price: "7650",
    categoryName: "category1",
    rating: 1.5,
    discount: 35,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 6",
    subtitle: "subtitle",
    price: "6300",
    categoryName: "category2",
    rating: 2.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 7",
    subtitle: "subtitle",
    price: "1380",
    categoryName: "category3",
    rating: 3.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 8",
    subtitle: "subtitle",
    price: "2870",
    categoryName: "category4",
    rating: 4.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 9",
    subtitle: "subtitle",
    price: "5440",
    categoryName: "category1",
    rating: 1.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 10",
    subtitle: "subtitle",
    price: "6800",
    categoryName: "category2",
    rating: 2.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 11",
    subtitle: "subtitle",
    price: "8700",
    categoryName: "category3",
    rating: 3.5,
    discount: 45,
    img: chair,
  },
  {
    _id: uuid(),
    title: "item 12",
    subtitle: "subtitle",
    price: "3750",
    categoryName: "category4",
    rating: 4.5,
    discount: 45,
    img: chair,
  },
];
