const actionTypes = {
  SORT_BY: "SORT_BY ",
  HIGH_TO_LOW: "HIGH_TO_LOW",
  CATEGORY1: "CATEGORY1",
  CATEGORY2: "CATEGORY2",
  CATEGORY3: "CATEGORY3",
  CATEGORY4: "CATEGORY4",
  RATING: "RATING",
  PRICE_RANGE: "PRICE_RANGE",
  CLEAR_ALL: "CLEAR_ALL",
};

export { actionTypes };
